CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    date_modified TIMESTAMP NOT NULL DEFAULT now(),
    folder_id INTEGER,
    content TEXT
);

ALTER TABLE noteful_notes ADD FOREIGN KEY (folder_id) REFERENCES noteful_folders (id)